from __future__ import annotations

import json

from src.reporting.render import write_daily_report
from src.utils.config import resolve_path


def test_orders_latest_output_fields_complete(tmp_path) -> None:
    report = {
        "as_of_date": "2026-04-03",
        "data_status": {"decision_scope_rows": 1, "degraded": False, "safe_mode": False, "orders_degraded": False, "notes": []},
        "portfolio_state": {"market_regime": "risk_on", "max_total_position": 1.0, "account_state": {"current_cash": 10000, "latest_total_equity": 20000}},
        "summary_action": "BUY_1:1",
        "errors": [],
        "notes": [],
        "decisions": [],
        "frozen_holdings": [],
        "force_exit_list": [],
        "universe_change_summary": [],
        "orders": [
            {
                "symbol": "600000.sh",
                "name": "测试股",
                "holding_state": "NONE",
                "current_position_tranches": 0,
                "target_position_tranches": 1,
                "current_weight": 0.0,
                "target_weight": 0.03,
                "target_position_change": 0.03,
                "current_shares": 0,
                "target_shares": 600,
                "delta_shares": 600,
                "rounded_lots": 6,
                "action_enum": "BUY_1",
                "strategy_intent": "BUY_1",
                "original_action_enum": "BUY_1",
                "execution_status": "EXECUTABLE",
                "execution_reason": "EXECUTABLE",
                "execution_reason_detail": "",
                "all_failed_checks": [],
                "unblock_hint": "",
                "execution_action_type": "NEW_BUY",
                "user_visible_action": True,
                "priority_score": 80.0,
                "action_reason": "满足第一笔买点。",
                "blocked_reason": None,
                "data_status": "ok",
                "latest_total_equity": 20000,
                "current_cash": 10000,
                "available_buying_power": 10000,
                "target_order_value": 600,
                "lot_notional": 100.0,
                "minimum_lot_order_value": 1500.0,
                "remaining_single_name_capacity": 2400.0,
                "compact_rank": 1,
                "replacement_candidate_symbol": None,
                "replacement_required": False,
                "pending_add_value": 0.0,
                "required_lot_notional": 100.0,
                "required_cash": 1500.0,
                "required_capacity": 100.0,
                "estimated_turnover": 600,
                "estimated_commission": 0.18,
                "estimated_stamp_duty": 0.0,
                "estimated_total_cash_impact": -600.18,
                "target_price_reference": 1.0,
            },
            {
                "symbol": "600001.sh",
                "name": "观察股",
                "holding_state": "NONE",
                "current_position_tranches": 0,
                "target_position_tranches": 0,
                "current_weight": 0.0,
                "target_weight": 0.0,
                "target_position_change": 0.0,
                "current_shares": 0,
                "target_shares": 0,
                "delta_shares": 0,
                "rounded_lots": 0,
                "action_enum": "HOLD",
                "strategy_intent": "BUY_1",
                "original_action_enum": "BUY_1",
                "execution_status": "WATCH",
                "execution_reason": "WATCH_PORTFOLIO_FULL",
                "execution_reason_detail": "组合已满。",
                "all_failed_checks": ["WATCH_PORTFOLIO_FULL"],
                "unblock_hint": "等待现有持仓退出。",
                "execution_action_type": "NEW_BUY",
                "user_visible_action": False,
                "priority_score": 70.0,
                "action_reason": "组合已满。",
                "blocked_reason": "",
                "data_status": "ok",
                "latest_total_equity": 20000,
                "current_cash": 10000,
                "available_buying_power": 10000,
                "target_order_value": 0,
                "lot_notional": 100.0,
                "minimum_lot_order_value": 1500.0,
                "remaining_single_name_capacity": 2400.0,
                "compact_rank": 2,
                "replacement_candidate_symbol": "600000.sh",
                "replacement_required": True,
                "pending_add_value": 0.0,
                "required_lot_notional": 100.0,
                "required_cash": 1500.0,
                "required_capacity": 100.0,
                "estimated_turnover": 0,
                "estimated_commission": 0,
                "estimated_stamp_duty": 0,
                "estimated_total_cash_impact": 0,
                "target_price_reference": 1.0,
            },
            {
                "symbol": "600002.sh",
                "name": "等待股",
                "holding_state": "ACTIVE",
                "current_position_tranches": 1,
                "target_position_tranches": 1,
                "current_weight": 0.03,
                "target_weight": 0.03,
                "target_position_change": 0.0,
                "current_shares": 100,
                "target_shares": 100,
                "delta_shares": 0,
                "rounded_lots": 0,
                "action_enum": "HOLD_WITH_PENDING_ADD",
                "strategy_intent": "BUY_2",
                "original_action_enum": "BUY_2",
                "execution_status": "PENDING",
                "execution_reason": "PENDING_LOT_ACCUMULATION_REQUIRED",
                "execution_reason_detail": "加仓缺口未累计到一手。",
                "all_failed_checks": ["PENDING_LOT_ACCUMULATION_REQUIRED"],
                "unblock_hint": "等待加仓缺口累计到一手。",
                "execution_action_type": "ADD",
                "user_visible_action": False,
                "priority_score": 65.0,
                "action_reason": "加仓等待。",
                "blocked_reason": "",
                "data_status": "ok",
                "latest_total_equity": 20000,
                "current_cash": 10000,
                "available_buying_power": 10000,
                "target_order_value": 0,
                "lot_notional": 100.0,
                "minimum_lot_order_value": 1500.0,
                "remaining_single_name_capacity": 1400.0,
                "compact_rank": 3,
                "replacement_candidate_symbol": None,
                "replacement_required": False,
                "pending_add_value": 500.0,
                "required_lot_notional": 100.0,
                "required_cash": 1500.0,
                "required_capacity": 100.0,
                "estimated_turnover": 0,
                "estimated_commission": 0,
                "estimated_stamp_duty": 0,
                "estimated_total_cash_impact": 0,
                "target_price_reference": 1.0,
            },
        ],
        "top_candidates_to_buy": [],
    }
    json_path = tmp_path / "daily.json"
    md_path = tmp_path / "daily.md"
    orders_json_path = tmp_path / "orders.json"
    orders_csv_path = tmp_path / "orders.csv"
    write_daily_report(report, json_path, md_path, orders_json_path, orders_csv_path)
    orders = json.loads(orders_json_path.read_text(encoding="utf-8"))
    expected = {
        "date",
        "symbol",
        "name",
        "holding_state",
        "current_position_tranches",
        "target_position_tranches",
        "current_weight",
        "target_weight",
        "target_position_change",
        "current_shares",
        "target_shares",
        "delta_shares",
        "rounded_lots",
        "action_enum",
        "strategy_intent",
        "original_action_enum",
        "execution_status",
        "execution_reason",
        "execution_reason_detail",
        "all_failed_checks",
        "unblock_hint",
        "execution_action_type",
        "user_visible_action",
        "priority_score",
        "action_reason",
        "blocked_reason",
        "data_status",
        "latest_total_equity",
        "current_cash",
        "available_buying_power",
        "target_order_value",
        "lot_notional",
        "minimum_lot_order_value",
        "remaining_single_name_capacity",
        "compact_rank",
        "replacement_candidate_symbol",
        "replacement_required",
        "pending_add_value",
        "required_lot_notional",
        "required_cash",
        "required_capacity",
        "estimated_turnover",
        "estimated_commission",
        "estimated_stamp_duty",
        "estimated_total_cash_impact",
        "target_price_reference",
    }
    assert expected.issubset(set(orders[0].keys()))
    assert orders[1]["user_visible_action"] is False
    assert orders[2]["execution_status"] == "PENDING"
    assert orders[2]["user_visible_action"] is False
    visible_manual_actions = [
        item
        for item in orders
        if item["user_visible_action"] is True
        and item["action_enum"] in {"BUY_1", "BUY_2", "BUY_3", "REDUCE", "SELL_ALL"}
    ]
    assert [item["symbol"] for item in visible_manual_actions] == ["600000.sh"]
    assert all(item["execution_status"] == "EXECUTABLE" for item in visible_manual_actions)
    csv_text = orders_csv_path.read_text(encoding="utf-8")
    assert "600001.sh" in csv_text
    assert "600002.sh" in csv_text
    markdown = md_path.read_text(encoding="utf-8")
    assert "账户执行诊断 / Execution diagnostics" in markdown
    assert "WATCH_PORTFOLIO_FULL: 1" in markdown


def test_daily_decision_prompt_only_explains_actions() -> None:
    prompt = resolve_path("prompts/daily_decision.md").read_text(encoding="utf-8")
    assert "不得修改、覆盖、重算任何 `action_enum`" in prompt
    assert "不得替代规则引擎决定买卖" in prompt
