from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from scripts import generate_50k_core_traces as traces


def make_trace_bundle(critical_missing: list[str] | None = None) -> traces.TraceBundle:
    daily = pd.DataFrame(
        [
            {
                "date": "2025-01-01",
                "variant": "trace_variant",
                "profile_name": "combined_v2_50k_core",
                "market_regime": "risk_on",
                "nav": 50000.0,
                "previous_nav": 50000.0,
                "daily_return": 0.0,
                "cumulative_return": 0.0,
                "cash": 30000.0,
                "cash_ratio": 0.60,
                "reserved_cash": 5000.0,
                "gross_exposure": 0.40,
                "net_exposure": 0.40,
                "positions_count": 1,
                "max_positions": 5,
                "average_position_weight": 0.40,
                "largest_position_weight": 0.40,
                "industry_count": 1,
                "largest_industry_weight": 0.40,
                "defensive_dividend_weight": 0.40,
                "cyclical_rotation_weight": 0.0,
                "realized_pnl_today": 0.0,
                "unrealized_pnl_today": 0.0,
                "total_pnl_today": 0.0,
                "fees_today": 0.0,
                "tax_today": 0.0,
                "slippage_today": 0.0,
                "turnover_today": 0.0,
                "buy_count_today": 1,
                "sell_count_today": 1,
                "reduce_count_today": 0,
                "replacement_count_today": 1,
                "raw_buy_count_today": 1,
                "account_actionable_buy_count_today": 0,
                "executable_buy_count_today": 0,
                "watch_only_count_today": 1,
                "top_watch_only_reason_today": "WATCH_ONLY_PORTFOLIO_FULL",
                "no_trade_reason_today": "PORTFOLIO_FULL",
                "risk_on_cash_drag_reason": "PORTFOLIO_FULL",
                "trace_quality_flag": "FULLY_SUPPORTED",
            },
            {
                "date": "2025-01-02",
                "variant": "trace_variant",
                "profile_name": "combined_v2_50k_core",
                "market_regime": "risk_on",
                "nav": 50500.0,
                "previous_nav": 50000.0,
                "daily_return": 0.01,
                "cumulative_return": 0.01,
                "cash": 29000.0,
                "cash_ratio": 29000.0 / 50500.0,
                "reserved_cash": 5050.0,
                "gross_exposure": 21500.0 / 50500.0,
                "net_exposure": 21500.0 / 50500.0,
                "positions_count": 1,
                "max_positions": 5,
                "average_position_weight": 21500.0 / 50500.0,
                "largest_position_weight": 21500.0 / 50500.0,
                "industry_count": 1,
                "largest_industry_weight": 21500.0 / 50500.0,
                "defensive_dividend_weight": 21500.0 / 50500.0,
                "cyclical_rotation_weight": 0.0,
                "realized_pnl_today": 0.0,
                "unrealized_pnl_today": 500.0,
                "total_pnl_today": 500.0,
                "fees_today": 0.0,
                "tax_today": 0.0,
                "slippage_today": 0.0,
                "turnover_today": 0.0,
                "buy_count_today": 0,
                "sell_count_today": 0,
                "reduce_count_today": 0,
                "replacement_count_today": 0,
                "raw_buy_count_today": 0,
                "account_actionable_buy_count_today": 0,
                "executable_buy_count_today": 0,
                "watch_only_count_today": 0,
                "top_watch_only_reason_today": "",
                "no_trade_reason_today": "NO_RAW_SIGNAL",
                "risk_on_cash_drag_reason": "NO_RAW_SIGNAL",
                "trace_quality_flag": "FULLY_SUPPORTED",
            },
        ]
    )
    position = pd.DataFrame(
        [
            {
                "date": "2025-01-02",
                "variant": "trace_variant",
                "symbol": "600000.sh",
                "name": "样本银行",
                "bucket": "defensive_dividend",
                "industry": "银行",
                "market_regime": "risk_on",
                "shares": 100,
                "previous_shares": 100,
                "close": 215.0,
                "previous_close": 210.0,
                "market_value": 21500.0,
                "previous_market_value": 21000.0,
                "position_weight": 21500.0 / 50500.0,
                "average_cost": 200.0,
                "cost_basis": 20000.0,
                "unrealized_pnl": 1500.0,
                "unrealized_pnl_pct": 0.075,
                "realized_pnl_today": 0.0,
                "unrealized_pnl_today": 500.0,
                "total_pnl_today": 500.0,
                "fees_allocated_today": 0.0,
                "tax_allocated_today": 0.0,
                "slippage_allocated_today": 0.0,
                "entry_date": "2025-01-01",
                "holding_days": 1,
                "last_buy_date": "2025-01-01",
                "last_sell_date": "",
                "entry_signal": "BUY_1",
                "latest_signal": "HOLD",
                "exit_signal_today": "",
                "replacement_sell_candidate": False,
                "replacement_buy_competitor": False,
                "relative_strength": 0.1,
                "ma20": 210,
                "ma60": 205,
                "ma120": 200,
                "ma250": 195,
                "ma20_slope_10d": 0.01,
                "ma120_slope_20d": 0.01,
                "stock_q_blended": 20,
                "industry_q_blended": 30,
                "expected_edge_score": 80,
                "score_components_json": "{}",
                "thesis_still_valid": True,
                "fundamental_break": False,
                "cycle_peak_trap": False,
                "trace_quality_flag": "FULLY_SUPPORTED",
            }
        ]
    )
    trade = pd.DataFrame(
        [
            {
                "trade_id": "T000001",
                "date": "2025-01-02",
                "signal_date": "2025-01-01",
                "variant": "trace_variant",
                "symbol": "600000.sh",
                "name": "样本银行",
                "bucket": "defensive_dividend",
                "industry": "银行",
                "side": "REPLACEMENT_BUY",
                "action_enum": "BUY_1",
                "action_source": "research_backtest_trace",
                "signal_level": "BUY_1",
                "entry_signal": "BUY_1",
                "exit_signal": "",
                "replacement_pair_id": "R000001",
                "is_replacement_sell": False,
                "is_replacement_buy": True,
                "shares": 100,
                "round_lot": 100,
                "lots": 1,
                "fill_price": 210.0,
                "previous_close": 209.0,
                "next_open": 210.0,
                "close": 215.0,
                "trade_value": 21000.0,
                "commission": 0.0,
                "stamp_tax": 0.0,
                "slippage": 0.0,
                "total_cost": 0.0,
                "cash_before": 50000.0,
                "cash_after": 29000.0,
                "shares_before": 0,
                "shares_after": 100,
                "position_value_before": 0.0,
                "position_value_after": 21500.0,
                "average_cost_before": 0.0,
                "average_cost_after": 210.0,
                "realized_pnl": 0.0,
                "realized_pnl_pct": 0.0,
                "holding_days_at_exit": "",
                "market_regime": "risk_on",
                "reason_codes_json": "[]",
                "blocked_reason_before_execution": "",
                "execution_status": "EXECUTED",
                "execution_reason": "open",
                "trace_quality_flag": "RESEARCH_ONLY_SIMULATED_NEXT_BAR",
            },
            {
                "trade_id": "T000002",
                "date": "2025-01-02",
                "signal_date": "2025-01-01",
                "variant": "trace_variant",
                "symbol": "600001.sh",
                "name": "替换卖出",
                "bucket": "defensive_dividend",
                "industry": "银行",
                "side": "REPLACEMENT_SELL",
                "action_enum": "SELL_ALL",
                "action_source": "research_backtest_trace",
                "signal_level": "SELL_ALL",
                "entry_signal": "BUY_1",
                "exit_signal": "SELL_ALL",
                "replacement_pair_id": "R000001",
                "is_replacement_sell": True,
                "is_replacement_buy": False,
                "shares": 100,
                "round_lot": 100,
                "lots": 1,
                "fill_price": 100.0,
                "previous_close": 101.0,
                "next_open": 100.0,
                "close": 99.0,
                "trade_value": 10000.0,
                "commission": 0.0,
                "stamp_tax": 0.0,
                "slippage": 0.0,
                "total_cost": 0.0,
                "cash_before": 40000.0,
                "cash_after": 50000.0,
                "shares_before": 100,
                "shares_after": 0,
                "position_value_before": 10100.0,
                "position_value_after": 0.0,
                "average_cost_before": 90.0,
                "average_cost_after": 0.0,
                "realized_pnl": 1000.0,
                "realized_pnl_pct": 0.111,
                "holding_days_at_exit": 40,
                "market_regime": "risk_on",
                "reason_codes_json": "[]",
                "blocked_reason_before_execution": "",
                "execution_status": "EXECUTED",
                "execution_reason": "open",
                "trace_quality_flag": "RESEARCH_ONLY_SIMULATED_NEXT_BAR",
            },
        ]
    )
    signal = pd.DataFrame(
        [
            {
                "date": "2025-01-01",
                "variant": "trace_variant",
                "symbol": "600000.sh",
                "name": "样本银行",
                "bucket": "defensive_dividend",
                "industry": "银行",
                "in_effective_universe": True,
                "market_regime": "risk_on",
                "raw_signal_generated": True,
                "raw_signal_type": "BUY_1",
                "strategy_intent": "BUY_1",
                "intended_action_enum": "BUY_1",
                "final_action_enum": "BUY_1",
                "user_visible_action": True,
                "account_actionable": True,
                "portfolio_actionable": True,
                "executable": True,
                "watch_only": False,
                "blocked": False,
                "pending": False,
                "skipped": False,
                "stage_failed": "NONE",
                "primary_failure_reason": "",
                "all_failure_reasons_json": "[]",
                "raw_buy_rank": 1,
                "compact_rank": 1,
                "expected_edge_score": 80,
                "score_components_json": "{}",
                "lot_notional": 21000,
                "target_position_budget": 9000,
                "lot_fit_status": "FIT",
                "structural_lot_block": False,
                "current_shares": 0,
                "current_weight": 0.0,
                "current_position_tranches": 0,
                "target_weight": 0.18,
                "target_shares": 100,
                "delta_shares": 100,
                "estimated_turnover": 21000,
                "available_cash_before": 50000,
                "cash_reserve_required": 5000,
                "max_positions": 5,
                "positions_count": 4,
                "industry_positions_count": 1,
                "industry_max_positions": 2,
                "replacement_candidate": True,
                "replacement_required": True,
                "replacement_triggered": True,
                "daily_new_position_limit_used": 1,
                "daily_add_limit_used": 0,
                "risk_on_cash_deploy_candidate": True,
                "trace_quality_flag": "FULLY_SUPPORTED",
            },
            {
                "date": "2025-01-01",
                "variant": "trace_variant",
                "symbol": "600002.sh",
                "name": "满仓候选",
                "bucket": "defensive_dividend",
                "industry": "银行",
                "in_effective_universe": True,
                "market_regime": "risk_on",
                "raw_signal_generated": True,
                "raw_signal_type": "BUY_1",
                "strategy_intent": "BUY_1",
                "intended_action_enum": "BUY_1",
                "final_action_enum": "HOLD",
                "user_visible_action": False,
                "account_actionable": False,
                "portfolio_actionable": False,
                "executable": False,
                "watch_only": True,
                "blocked": True,
                "pending": False,
                "skipped": False,
                "stage_failed": "PORTFOLIO_FULL",
                "primary_failure_reason": "WATCH_ONLY_PORTFOLIO_FULL",
                "all_failure_reasons_json": '["WATCH_ONLY_PORTFOLIO_FULL"]',
                "raw_buy_rank": 2,
                "compact_rank": 2,
                "expected_edge_score": 70,
                "score_components_json": "{}",
                "lot_notional": 5000,
                "target_position_budget": 9000,
                "lot_fit_status": "FIT",
                "structural_lot_block": False,
                "current_shares": 0,
                "current_weight": 0.0,
                "current_position_tranches": 0,
                "target_weight": 0.18,
                "target_shares": 100,
                "delta_shares": 100,
                "estimated_turnover": 5000,
                "available_cash_before": 50000,
                "cash_reserve_required": 5000,
                "max_positions": 5,
                "positions_count": 5,
                "industry_positions_count": 1,
                "industry_max_positions": 2,
                "replacement_candidate": False,
                "replacement_required": True,
                "replacement_triggered": False,
                "daily_new_position_limit_used": 1,
                "daily_add_limit_used": 0,
                "risk_on_cash_deploy_candidate": False,
                "trace_quality_flag": "FULLY_SUPPORTED",
            },
        ]
    )
    exit_trace = pd.DataFrame(
        [
            {
                "date": "2025-01-01",
                "variant": "trace_variant",
                "symbol": "600001.sh",
                "bucket": "defensive_dividend",
                "industry": "银行",
                "market_regime": "risk_on",
                "shares": 100,
                "position_weight": 0.2,
                "holding_days": 40,
                "unrealized_pnl_pct": -0.09,
                "close": 99,
                "ma20": 101,
                "ma60": 102,
                "ma120": 110,
                "ma250": 115,
                "ma20_slope_10d": -0.01,
                "ma120_slope_20d": -0.01,
                "stock_q_blended": 65,
                "industry_q_blended": 40,
                "relative_strength": -0.1,
                "thesis_still_valid": False,
                "fundamental_break": False,
                "cycle_peak_trap": False,
                "valuation_reversion_exit_triggered": True,
                "soft_trim_triggered": False,
                "trend_stop_triggered": False,
                "would_have_triggered_trend_stop": True,
                "trend_stop_disabled_by_profile": True,
                "partial_derisk_triggered": False,
                "partial_derisk_profile_state": "disabled_by_profile",
                "cycle_peak_trap_trend_break_triggered": False,
                "replacement_sell_triggered": True,
                "force_exit_triggered": False,
                "selected_exit_action": "SELL_ALL",
                "selected_exit_reason": "replacement",
                "exit_priority_order_json": "[]",
                "reduce_or_sell_shares": 100,
                "reduce_or_sell_lots": 1,
                "exit_executable": True,
                "exit_blocked_reason": "",
                "missed_exit_candidate": False,
                "missed_exit_reason": "",
                "trace_quality_flag": "FULLY_SUPPORTED",
            }
        ]
    )
    replacement = pd.DataFrame(
        [
            {
                "date": "2025-01-01",
                "variant": "trace_variant",
                "portfolio_full": True,
                "candidate_symbol": "600000.sh",
                "candidate_name": "样本银行",
                "candidate_bucket": "defensive_dividend",
                "candidate_industry": "银行",
                "candidate_score": 80,
                "candidate_lot_notional": 21000,
                "candidate_lot_fit_status": "FIT",
                "candidate_structural_lot_block": False,
                "candidate_account_actionable": True,
                "candidate_expected_edge_score": 80,
                "weakest_holding_symbol": "600001.sh",
                "weakest_holding_name": "替换卖出",
                "weakest_holding_bucket": "defensive_dividend",
                "weakest_holding_industry": "银行",
                "weakest_holding_score": 60,
                "weakest_holding_unrealized_pnl_pct": -0.09,
                "weakest_holding_holding_days": 40,
                "weakest_holding_relative_strength": -0.1,
                "weakest_holding_thesis_still_valid": False,
                "weakest_holding_fundamental_break": False,
                "score_gap": 20,
                "score_gap_threshold": 8,
                "min_holding_days_before_replacement": 40,
                "max_replacements_per_month": 1,
                "current_month_replacement_count": 0,
                "replacement_triggered": True,
                "replacement_pair_id": "R000001",
                "reason_not_triggered": "",
                "all_replacement_checks_json": "{}",
                "diagnostic_future_return_20d_candidate": 0.05,
                "diagnostic_future_return_20d_weakest": -0.02,
                "diagnostic_opportunity_cost_20d": 0.07,
                "diagnostic_future_return_60d_candidate": 0.06,
                "diagnostic_future_return_60d_weakest": -0.01,
                "diagnostic_opportunity_cost_60d": 0.07,
                "diagnostic_only": True,
                "trace_quality_flag": "DIAGNOSTIC_ONLY_FUTURE_RETURN",
            }
        ]
    )
    drawdown = pd.DataFrame(
        [
            {
                "drawdown_id": 1,
                "start_date": "2025-01-01",
                "trough_date": "2025-01-02",
                "recovery_date": "",
                "max_drawdown": -0.02,
                "date": "2025-01-02",
                "symbol": "600000.sh",
                "bucket": "defensive_dividend",
                "industry": "银行",
                "market_regime": "risk_on",
                "position_weight_at_start": 0.4,
                "position_weight_at_trough": 0.42,
                "pnl_contribution_during_drawdown": -500,
                "return_contribution_during_drawdown": -0.01,
                "realized_pnl_during_drawdown": 0,
                "unrealized_pnl_during_drawdown": -500,
                "exit_signal_count_during_drawdown": 1,
                "exit_triggered_during_drawdown": True,
                "replacement_candidate_count_during_drawdown": 1,
                "replacement_triggered_during_drawdown": True,
                "missed_exit_candidate": False,
                "missed_replacement_candidate": False,
                "trace_quality_flag": "FULLY_SUPPORTED",
            }
        ]
    )
    risk_cash = pd.DataFrame(
        [
            {
                "date": "2025-01-01",
                "variant": "trace_variant",
                "market_regime": "risk_on",
                "cash_ratio": 0.6,
                "gross_exposure": 0.4,
                "positions_count": 5,
                "max_positions": 5,
                "raw_buy_count": 1,
                "account_actionable_buy_count": 0,
                "portfolio_actionable_buy_count": 0,
                "executable_buy_count": 0,
                "watch_only_count": 1,
                "replacement_candidate_count": 1,
                "replacement_triggered_count": 1,
                "top_expected_edge_candidate": "600000.sh",
                "top_expected_edge_score": 80,
                "top_candidate_failure_reason": "PORTFOLIO_FULL",
                "reason_cash_not_deployed": "PORTFOLIO_FULL",
                "deployable_cash_estimate": 12500,
                "target_cash_ratio": 0.35,
                "cash_gap_to_target": 0.25,
                "trace_quality_flag": "FULLY_SUPPORTED",
            }
        ]
    )
    intervals = pd.DataFrame(
        [
            {
                "interval_id": 1,
                "start_date": "2025-01-01",
                "end_date": "2025-01-02",
                "trading_days": 2,
                "months_covered": 1,
                "dominant_market_regime": "risk_on",
                "avg_cash_ratio": 0.58,
                "avg_exposure": 0.42,
                "avg_positions_count": 5,
                "raw_buy_days": 1,
                "account_actionable_days": 0,
                "executable_buy_days": 0,
                "watch_only_days": 1,
                "replacement_candidate_days": 1,
                "top_failure_reasons_json": '{"PORTFOLIO_FULL": 1}',
                "best_candidate_symbol_during_interval": "600000.sh",
                "best_candidate_score_during_interval": 80,
                "reason_no_trade_summary": "PORTFOLIO_FULL",
                "trace_quality_flag": "FULLY_SUPPORTED",
            }
        ]
    )
    missing = {
        "research_only": True,
        "critical_missing": critical_missing or [],
        "partial_limitations": ["lot_level_cost_basis: unavailable; using FIFO_APPROX_AVG_COST"],
        "tables": {
            "daily_portfolio_ledger": {"rows": len(daily), "missing_columns": []},
            "daily_position_pnl": {"rows": len(position), "missing_columns": []},
            "trade_ledger": {"rows": len(trade), "missing_columns": []},
            "signal_execution_trace": {"rows": len(signal), "missing_columns": []},
            "exit_rule_trace": {"rows": len(exit_trace), "missing_columns": []},
            "replacement_candidate_trace": {"rows": len(replacement), "missing_columns": []},
        },
    }
    effective = {
        "profile_name": "combined_v2_50k_core",
        "research_only": True,
        "auto_trading_approved": False,
        "broker_integration_enabled": False,
        "llm_decision_allowed": False,
        "writes_real_trades": False,
        "release_profile_replacement": False,
    }
    return traces.TraceBundle(daily, position, trade, signal, exit_trace, replacement, drawdown, risk_cash, intervals, missing, effective)


def test_trace_generation_writes_required_outputs(tmp_path: Path) -> None:
    traces.write_trace_outputs(make_trace_bundle(), tmp_path, allow_missing=True)

    for name in traces.REQUIRED_TRACE_OUTPUTS:
        assert (tmp_path / name).exists(), name


def test_allow_missing_records_missing_and_strict_fails(tmp_path: Path) -> None:
    bundle = make_trace_bundle(["daily_portfolio_ledger.nav"])
    traces.write_trace_outputs(bundle, tmp_path / "allow", allow_missing=True)
    assert "daily_portfolio_ledger.nav" in (tmp_path / "allow" / "trace_missing_fields.json").read_text()

    with pytest.raises(RuntimeError):
        traces.write_trace_outputs(bundle, tmp_path / "strict", strict=True)
